#+TITLE: README for slime-the-world
#+AUTHOR: Jakob L. Kreuze
#+EMAIL: zerodaysfordays@sdf.lonestar.org
#+DATE:	<2018-10-19 Fri>

This is my entry to this year's [[https://events.tymoon.eu/4][Autumn Lisp Game Jam]]. The dialect of Lisp I
chose to use for this entry was [[https://fennel-lang.org/][Fennel]], a simple and elegant Lisp that I feel
perfectly matches the simplicity and elegance of Lua. The theme was slime, so
it's a game about covering everything in sight with slime. As of right now, this
has the distinct charm of a demo that was far too ambitious and rushed to be
much more than a buggy proof of concept, but I do hope that enjoy it in some
capacity.

The game's code is licensed under version 3 of the GNU General Public License,
and the artwork in =art/= with the exception of =font.png= is licensed under the
Creative Commons Attribution-ShareAlike 4.0 International License. A copy of the
GPL is available at =LICENSE=, and to view a copy of the CC BY-SA 4.0, visit
http://creativecommons.org/licenses/by-sa/4.0/ or send a letter to Creative
Commons, PO Box 1866, Mountain View, CA 94042, USA. The contents of =music/= are
in the public domain, and the =art/font.png= is licensed under the CC0.

* 1. Running the Game

You will need the [[https://love2d.org/][LÖVE2D]] engine. Once you've obtained that, you can run the
following from the root directory:

#+BEGIN_SRC sh
love .
#+END_SRC

* 2. Instructions

You can move laterally with the left and right arrow keys, jump with the 'z'
key, and spew balls of slime with the 'x' key.

* 3. Thanks!

** [[https://technomancy.us][Phil Hagelberg]]

I'm totally new to LÖVE and Fennel, so I borrowed a lot of the boilerplate from
his entry to the [[https://itch.io/jam/lisp-game-jam-2018/results][Lisp Game Jam 2018]], [[https://gitlab.com/technomancy/exo-encounter-667][EXO_encounter 667]]. His post, [[https://technomancy.us/188]["in which a
game jam is recounted further"]], also served as excellent guidance in navigating
the API's for LÖVE as well as a few other excellent Lua libraries, listed below.

** [[https://github.com/rxi][rxi]]

Of [[https://github.com/rxi/lume][lume.lua]], which provides some very pleasant functional constructs such as
=map=, as well as typical linear interpolation and vector math. lume is released
under the MIT license.

** [[http://kiki.to/][Enrique García Cota]]

Of [[https://github.com/kikito/bump.lua][bump.lua]], a much simpler library for collision detection than the one
provided by LÖVE. bump.lua is released under the MIT license.

** [[http://clintbellanger.net/][Clint Bellanger]]

Of the [[https://opengameart.org/content/boxy-bold-font][Boxy Bold Font]] that I used in this game. The font is licensed under CC0.

** [[https://love2d.org/][LOVE Development Team]]

I really did fall in löve with the LÖVE API's.

** [[http://www.drpetter.se/about.html][Tomas Pettersson]]

Of [[http://www.drpetter.se/project_sfxr.html][sfxr]], the tool I used to produce the jumping and spitting sound effects. sfxr
is released under the MIT license.

** Various Users on The Mod Archive

The wonderful chiptunes are, sadly, not my own. To fit into the requirement that
all existing assets be free for others to use as well, I only picked modules
that were licensed in the public domain. Among them:

- [[https://modarchive.org/index.php?request=view_by_moduleid&query=50010][Nebulos NES by SoDa7]]
- [[https://modarchive.org/index.php?request=view_by_moduleid&query=172462][SpeedChip by KatieCadetAKASailorMoonFan]]
- [[https://modarchive.org/index.php?request=view_by_moduleid&query=173084][October_Chip by Drozerix]]
- [[https://modarchive.org/index.php?request=view_by_moduleid&query=172732][The_Dim_Dungeon by Drozerix]]
- [[https://modarchive.org/index.php?request=view_by_moduleid&query=172424][The_Epic_Chip by Drozerix]]
- [[https://modarchive.org/index.php?request=view_by_moduleid&query=173935][Girl From Mars by Drozerix]]
- [[https://modarchive.org/index.php?request=view_by_moduleid&query=173939][Key Generators by Drozerix]]
